In [10]:
import torch
import numpy as np


In [11]:
torch.tensor([[1.0, -1.0], [1.0, -1.0]])


tensor([[ 1., -1.],
        [ 1., -1.]])

In [14]:
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))


tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
torch.empty([3, 4])


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
torch.ones([3,  4])


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])