In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


### 1. 逻辑运算

In [4]:
score = np.random.randint(40, 100, (10, 5))
test_score = score[6:, :]
test_score


array([[89, 61, 76, 61, 67],
       [75, 78, 69, 56, 87],
       [96, 84, 47, 81, 68],
       [47, 97, 93, 75, 43]])

In [5]:
test_score > 60


array([[ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True, False,  True,  True],
       [False,  True,  True,  True, False]])

In [7]:
test_score[test_score > 60] = 1
test_score


array([[ 1,  1,  1,  1,  1],
       [ 1,  1,  1, 56,  1],
       [ 1,  1, 47,  1,  1],
       [47,  1,  1,  1, 43]])

### 2. 通用判断函数

In [8]:
np.all(score[0:2, :] > 60)


False

In [9]:
np.any(score[0:2, :] > 80)


True

### 3. 三元运算符

In [10]:
temp = score[:4, :4]
np.where(temp > 60, 1, 0)


array([[1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 1, 0, 1]])

In [12]:
np.where(np.logical_and(temp > 60, temp < 90), 1, 0)
np.where(np.logical_or(temp > 90, temp < 60), 1, 0)


array([[0, 1, 1, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 1, 1, 1]])

### 4. 统计运算

In [13]:
temp = score[:4, :]
temp


array([[82, 52, 93, 72, 73],
       [73, 86, 67, 67, 62],
       [84, 92, 84, 64, 94],
       [47, 98, 59, 99, 50]])

In [15]:
print("max: {}".format(np.max(temp, axis=0)))
print("min: {}".format(np.min(temp, axis=0)))
print("std: {}".format(np.std(temp, axis=0)))
print("mean: {}".format(np.mean(temp, axis=0)))


max: [84 98 93 99 94]
min: [47 52 59 64 50]
std: [14.73940297 17.8325545  13.44200506 13.86542462 16.19220491]
mean: [71.5  82.   75.75 75.5  69.75]


In [16]:
np.argmax(temp, axis=0)


array([2, 3, 0, 3, 2])