In [1]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd

In [2]:
arr = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])

In [3]:
arr + 1

array([[2, 3, 4, 3, 2, 5],
       [6, 7, 2, 3, 4, 2]])

In [4]:
arr / 2

array([[0.5, 1. , 1.5, 1. , 0.5, 2. ],
       [2.5, 3. , 0.5, 1. , 1.5, 0.5]])

In [5]:
a = [1, 2, 3, 4, 5]
a * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [6]:
arr1 = np.array([[0], [1], [2], [3]])
arr1

array([[0],
       [1],
       [2],
       [3]])

In [7]:
arr1.shape

(4, 1)

In [8]:
arr2 = np.array([1, 2, 3])
arr2

array([1, 2, 3])

In [9]:
arr2.shape

(3,)

In [10]:
arr1 + arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])