In [1]:
import numpy as np
import pandas as pd


### 1. Series

In [2]:
pd.Series(np.arange(10))


0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [3]:
pd.Series([6.7, 5.6, 3, 10, 2], index=[1, 2, 3, 4, 5])


1     6.7
2     5.6
3     3.0
4    10.0
5     2.0
dtype: float64

In [5]:
color_count = pd.Series({"red": 100, "blue": 200, "green": 500, "yellow": 1000})
color_count


red        100
blue       200
green      500
yellow    1000
dtype: int64

In [6]:
color_count.index


Index(['red', 'blue', 'green', 'yellow'], dtype='object')

In [7]:
color_count.keys()


Index(['red', 'blue', 'green', 'yellow'], dtype='object')

In [8]:
color_count.values


array([ 100,  200,  500, 1000])

In [9]:
color_count[2]


500

### 2. DataFrame

In [10]:
pd.DataFrame(np.random.randn(2, 3))


0         1         2
0  0.896724  0.341792  0.786407
1  0.596456 -0.247196 -0.718330

In [12]:
score = np.random.randint(40, 100, (10, 5))
score


array([[61, 50, 45, 43, 81],
       [56, 88, 65, 51, 48],
       [90, 55, 76, 78, 56],
       [44, 60, 62, 70, 92],
       [72, 95, 89, 69, 65],
       [76, 66, 63, 71, 63],
       [60, 91, 92, 91, 82],
       [79, 79, 98, 93, 60],
       [71, 55, 49, 82, 96],
       [53, 76, 46, 79, 76]])

In [14]:
score_df = pd.DataFrame(score)
score_df


0   1   2   3   4
0  61  50  45  43  81
1  56  88  65  51  48
2  90  55  76  78  56
3  44  60  62  70  92
4  72  95  89  69  65
5  76  66  63  71  63
6  60  91  92  91  82
7  79  79  98  93  60
8  71  55  49  82  96
9  53  76  46  79  76

In [16]:
subjects = ["语文", "数学", "英语", "政治", "体育"]
stu = ['同学' + str(i) for i in range(score_df.shape[0])]

data = pd.DataFrame(score, columns=subjects, index=stu)
data


语文  数学  英语  政治  体育
同学0  61  50  45  43  81
同学1  56  88  65  51  48
同学2  90  55  76  78  56
同学3  44  60  62  70  92
同学4  72  95  89  69  65
同学5  76  66  63  71  63
同学6  60  91  92  91  82
同学7  79  79  98  93  60
同学8  71  55  49  82  96
同学9  53  76  46  79  76

In [17]:
data.shape


(10, 5)

In [18]:
data.index


Index(['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9'], dtype='object')

In [19]:
data.columns


Index(['语文', '数学', '英语', '政治', '体育'], dtype='object')

In [20]:
data.values


array([[61, 50, 45, 43, 81],
       [56, 88, 65, 51, 48],
       [90, 55, 76, 78, 56],
       [44, 60, 62, 70, 92],
       [72, 95, 89, 69, 65],
       [76, 66, 63, 71, 63],
       [60, 91, 92, 91, 82],
       [79, 79, 98, 93, 60],
       [71, 55, 49, 82, 96],
       [53, 76, 46, 79, 76]])

In [21]:
data.T


同学0  同学1  同学2  同学3  同学4  同学5  同学6  同学7  同学8  同学9
语文   61   56   90   44   72   76   60   79   71   53
数学   50   88   55   60   95   66   91   79   55   76
英语   45   65   76   62   89   63   92   98   49   46
政治   43   51   78   70   69   71   91   93   82   79
体育   81   48   56   92   65   63   82   60   96   76

In [22]:
data.head(5)


语文  数学  英语  政治  体育
同学0  61  50  45  43  81
同学1  56  88  65  51  48
同学2  90  55  76  78  56
同学3  44  60  62  70  92
同学4  72  95  89  69  65

In [23]:
data.tail(5)


语文  数学  英语  政治  体育
同学5  76  66  63  71  63
同学6  60  91  92  91  82
同学7  79  79  98  93  60
同学8  71  55  49  82  96
同学9  53  76  46  79  76

In [24]:
stu = ["学生_" + str(i) for i in range(score_df.shape[0])]
data.index = stu


In [25]:
data


语文  数学  英语  政治  体育
学生_0  61  50  45  43  81
学生_1  56  88  65  51  48
学生_2  90  55  76  78  56
学生_3  44  60  62  70  92
学生_4  72  95  89  69  65
学生_5  76  66  63  71  63
学生_6  60  91  92  91  82
学生_7  79  79  98  93  60
学生_8  71  55  49  82  96
学生_9  53  76  46  79  76

In [26]:
data.reset_index()

index  语文  数学  英语  政治  体育
0  学生_0  61  50  45  43  81
1  学生_1  56  88  65  51  48
2  学生_2  90  55  76  78  56
3  学生_3  44  60  62  70  92
4  学生_4  72  95  89  69  65
5  学生_5  76  66  63  71  63
6  学生_6  60  91  92  91  82
7  学生_7  79  79  98  93  60
8  学生_8  71  55  49  82  96
9  学生_9  53  76  46  79  76

In [27]:
data.reset_index(drop=True)

语文  数学  英语  政治  体育
0  61  50  45  43  81
1  56  88  65  51  48
2  90  55  76  78  56
3  44  60  62  70  92
4  72  95  89  69  65
5  76  66  63  71  63
6  60  91  92  91  82
7  79  79  98  93  60
8  71  55  49  82  96
9  53  76  46  79  76

In [33]:
df = pd.DataFrame({'month': [1, 4, 7, 10], 'year': [2012, 2014, 2013, 2014], 'sale': [55, 40, 84, 31]})
df 

month  year  sale
0      1  2012    55
1      4  2014    40
2      7  2013    84
3     10  2014    31

In [30]:
# df.set_index("month")


year  sale
month            
1      2012    55
4      2014    40
7      2013    84
10     2014    31

In [34]:
df = df.set_index(["year", "month"])
df

sale
year month      
2012 1        55
2014 4        40
2013 7        84
2014 10       31

### 2. MultiIndex和Panel

In [35]:
df.index

MultiIndex([(2012,  1),
            (2014,  4),
            (2013,  7),
            (2014, 10)],
           names=['year', 'month'])

In [36]:
df.index.names

FrozenList(['year', 'month'])

In [37]:
df.index.levels

FrozenList([[2012, 2013, 2014], [1, 4, 7, 10]])

In [38]:
arrays = [[1, 1, 2, 2], ['red', 'blue', 'red', 'blue']]
pd.MultiIndex.from_arrays(arrays=arrays, names=("number", "color"))

MultiIndex([(1,  'red'),
            (1, 'blue'),
            (2,  'red'),
            (2, 'blue')],
           names=['number', 'color'])